# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: run-pytests
        name: Run pytest
        entry: pytest -q
        language: system
        pass_filenames: false
        always_run: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
