# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run unit & integration tests (pytest)
        run: |
          pwd
          ls -la
          echo "Current PYTHONPATH: $PYTHONPATH"
          python -c "import sys; print('Python path:', sys.path)"
          PYTHONPATH=$PWD pytest -q
